# -*- coding: utf-8 -*-
"""House_Sales_in_King_Count_USA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_LeHdFy0b1AMp7o8c07Ekfrluvqmr_1

<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDA0101ENSkillsNetwork20235326-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align=center><font size = 5>Data Analysis with Python</font></h1>

# House Sales in King County, USA

This dataset contains house sale prices for King County, which includes Seattle. It includes homes sold between May 2014 and May 2015.

| Variable      | Description                                                                                                 |
| ------------- | ----------------------------------------------------------------------------------------------------------- |
| id            | A notation for a house                                                                                      |
| date          | Date house was sold                                                                                         |
| price         | Price is prediction target                                                                                  |
| bedrooms      | Number of bedrooms                                                                                          |
| bathrooms     | Number of bathrooms                                                                                         |
| sqft_living   | Square footage of the home                                                                                  |
| sqft_lot      | Square footage of the lot                                                                                   |
| floors        | Total floors (levels) in house                                                                              |
| waterfront    | House which has a view to a waterfront                                                                      |
| view          | Has been viewed                                                                                             |
| condition     | How good the condition is overall                                                                           |
| grade         | overall grade given to the housing unit, based on King County grading system                                |
| sqft_above    | Square footage of house apart from basement                                                                 |
| sqft_basement | Square footage of the basement                                                                              |
| yr_built      | Built Year                                                                                                  |
| yr_renovated  | Year when house was renovated                                                                               |
| zipcode       | Zip code                                                                                                    |
| lat           | Latitude coordinate                                                                                         |
| long          | Longitude coordinate                                                                                        |
| sqft_living15 | Living room area in 2015(implies-- some renovations) This might or might not have affected the lotsize area |
| sqft_lot15    | LotSize area in 2015(implies-- some renovations)                                                            |
"""

#After executing the below command restart the kernel and run all cells.
!pip3 install scikit-learn --upgrade --user

"""You will require the following libraries:

"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.linear_model import LinearRegression
# %matplotlib inline

"""# Module 1: Importing Data Sets

Load the csv:
"""

file_name='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/FinalModule_Coursera/data/kc_house_data_NaN.csv'
df=pd.read_csv(file_name)

"""We use the method <code>head</code> to display the first 5 columns of the dataframe.

"""

df.head()

"""### Question 1

Display the data types of each column using the function dtypes, then take a screenshot and submit it, include your code in the image.

"""

# Muestra el tipo de datos de cada columna
print(df.dtypes)

"""We use the method describe to obtain a statistical summary of the dataframe.

"""

df.describe()

"""# Module 2: Data Wrangling

### Question 2

Drop the columns <code>"id"</code>  and <code>"Unnamed: 0"</code> from axis 1 using the method <code>drop()</code>, then use the method <code>describe()</code> to obtain a statistical summary of the data. Take a screenshot and submit it, make sure the <code>inplace</code> parameter is set to <code>True</code>
"""

# Drop the columns 'id' and 'Unnamed: 0'
df.drop(['id', 'Unnamed: 0'], axis=1, inplace=True)

# Display the statistical summary of the data
df.describe()

"""We can see we have missing values for the columns <code> bedrooms</code>  and <code> bathrooms </code>

"""

print("number of NaN values for the column bedrooms :", df['bedrooms'].isnull().sum())
print("number of NaN values for the column bathrooms :", df['bathrooms'].isnull().sum())

"""We can replace the missing values of the column <code>'bedrooms'</code> with the mean of the column  <code>'bedrooms' </code> using the method <code>replace()</code>. Don't forget to set the <code>inplace</code> parameter to <code>True</code>

"""

mean=df['bedrooms'].mean()
df['bedrooms'].replace(np.nan,mean, inplace=True)

"""We also replace the missing values of the column <code>'bathrooms'</code> with the mean of the column  <code>'bathrooms' </code> using the method <code>replace()</code>. Don't forget to set the <code> inplace </code>  parameter top <code> True </code>

"""

mean=df['bathrooms'].mean()
df['bathrooms'].replace(np.nan,mean, inplace=True)

print("number of NaN values for the column bedrooms :", df['bedrooms'].isnull().sum())
print("number of NaN values for the column bathrooms :", df['bathrooms'].isnull().sum())

"""# Module 3: Exploratory Data Analysis

### Question 3

Use the method <code>value_counts</code> to count the number of houses with unique floor values, use the method <code>.to_frame()</code> to convert it to a dataframe.
"""

# 1. Selecciona la columna 'floors' (una columna categórica en este conjunto de datos)
# y usa value_counts() para contar las ocurrencias únicas.
floor_counts = df['floors'].value_counts()

# 2. Convierte la Serie resultante a un DataFrame usando to_frame().
floor_df = floor_counts.to_frame()

# 3. Muestra el DataFrame resultante.
print(floor_df)

"""### Question 4

Use the function <code>boxplot</code> in the seaborn library  to  determine whether houses with a waterfront view or without a waterfront view have more price outliers.

"""

# --- Código Clave para el Boxplot ---

# 2. Crea el gráfico de caja (Boxplot)
# Eje X: 'waterfront' (Variable categórica: con/sin vista al mar)
# Eje Y: 'price' (Variable numérica: precio)
plt.figure(figsize=(10, 6))
sns.boxplot(x='waterfront', y='price', data=df)

# Añade título y etiquetas para claridad
plt.title('Distribución de Precio por Vista al Mar (Waterfront)')
plt.xlabel('Vista al Mar (0: No, 1: Sí)')
plt.ylabel('Precio')

# Muestra el gráfico
plt.show()

"""### Question 5

Use the function <code>regplot</code>  in the seaborn library  to  determine if the feature <code>sqft_above</code> is negatively or positively correlated with price.

"""

# Use regplot to determine if sqft_above is negatively or positively correlated with price
sns.regplot(x='sqft_above', y='price', data=df)
plt.show()

"""We can use the Pandas method <code>corr()</code>  to find the feature other than price that is most correlated with price.

"""

# Exclude the 'date' column and calculate the correlation
df.drop('date', axis=1).corr()['price'].sort_values()

"""# Module 4: Model Development

We can Fit a linear regression model using the  longitude feature <code>'long'</code> and  caculate the R^2.
"""

X = df[['long']]
Y = df['price']
lm = LinearRegression()
lm.fit(X,Y)
lm.score(X, Y)

"""### Question  6

Fit a linear regression model to predict the <code>'price'</code> using the feature <code>'sqft_living'</code> then calculate the R^2. Take a screenshot of your code and the value of the R^2.

"""

# --- 1. Preparación de los datos (Ajusta los nombres de las columnas si es necesario) ---
# En un dataset de casas, 'price' y 'sqft_living' son comunes.
# Si el DataFrame usa índices numéricos, reemplaza 'price' y 'sqft_living' por 19 y 5, por ejemplo.

from sklearn.metrics import r2_score # Import r2_score

# Variable predictora (X)
X = df[['sqft_living']]

# Variable objetivo (Y)
Y = df['price']

# Opcional: Dividir datos para evaluación
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

# --- 2. Crear y Entrenar el Modelo de Regresión Lineal ---
# Crea el objeto de regresión lineal
Lm = LinearRegression()

# Entrena el modelo con todos los datos (ya que el objetivo es solo calcular el R^2)
Lm.fit(X, Y)

# --- 3. Calcular el R^2 ---
# Realiza la predicción usando la variable 'sqft_living'
Y_pred = Lm.predict(X)

# Calcula el R^2 (Coeficiente de Determinación)
r2 = r2_score(Y, Y_pred)

# --- 4. Mostrar el Resultado ---
print("El coeficiente de R^2 es:")
print(r2)

"""### Question 7

Fit a linear regression model to predict the <code>'price'</code> using the list of features:

"""

features =["floors", "waterfront","lat" ,"bedrooms" ,"sqft_basement" ,"view" ,"bathrooms","sqft_living15","sqft_above","grade","sqft_living"]

"""Then calculate the R^2. Take a screenshot of your code.

"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# --- Paso 1: Cargar el DataFrame (Asegúrate de que esta línea funcione en tu entorno) ---
# Si tu archivo no tiene encabezados, recuerda usar: df = pd.read_csv(filePath, header=None)
# Aquí se asume que el DataFrame 'df' ya está cargado con los nombres de columna correctos.

# 2. Definir la lista de variables predictoras (X)
# Esta es la lista de características que estás usando para la predicción.
Features = ['floors', 'waterfront', 'lat', 'sqft_living', 'bedrooms']

# 3. Crear las matrices de datos
# X: DataFrame con las variables predictoras (Características)
X = df[Features]
# Y: Serie con la variable objetivo (Precio)
Y = df['price']

# 4. Inicializar y Entrenar el Modelo
Lm = LinearRegression()
Lm.fit(X, Y)

# 5. Realizar Predicciones y Calcular el R^2
Y_pred = Lm.predict(X)
r2_multiple = r2_score(Y, Y_pred)

# 6. Mostrar el R^2
print("El Coeficiente de Determinación (R^2) del Modelo Múltiple es:")
print(r2_multiple)

"""### This will help with Question 8

Create a list of tuples, the first element in the tuple contains the name of the estimator:

<code>'scale'</code>

<code>'polynomial'</code>

<code>'model'</code>

The second element in the tuple  contains the model constructor

<code>StandardScaler()</code>

<code>PolynomialFeatures(include_bias=False)</code>

<code>LinearRegression()</code>

"""

Input=[('scale',StandardScaler()),('polynomial', PolynomialFeatures(include_bias=False)),('model',LinearRegression())]

"""### Question 8

Use the list to create a pipeline object to predict the 'price', fit the object using the features in the list <code>features</code>, and calculate the R^2.

"""

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Create a pipeline object
pipe = Pipeline(Input)

# Define the features to use
features =["floors", "waterfront","lat" ,"bedrooms" ,"sqft_basement" ,"view" ,"bathrooms","sqft_living15","sqft_above","grade","sqft_living"]
X = df[features]
Y = df['price']

# Fit the pipeline to the data
pipe.fit(X, Y)

# Make predictions
Y_pred_pipe = pipe.predict(X)

# Calculate the R^2
r2_pipe = r2_score(Y, Y_pred_pipe)

# Print the R^2
print("R^2 for the pipeline model:", r2_pipe)

"""# Module 5: Model Evaluation and Refinement

Import the necessary modules:
"""

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
print("done")

"""We will split the data into training and testing sets:

"""

features =["floors", "waterfront","lat" ,"bedrooms" ,"sqft_basement" ,"view" ,"bathrooms","sqft_living15","sqft_above","grade","sqft_living"]
X = df[features]
Y = df['price']

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state=1)


print("number of test samples:", x_test.shape[0])
print("number of training samples:",x_train.shape[0])

"""### Question 9

Create and fit a Ridge regression object using the training data, set the regularization parameter to 0.1, and calculate the R^2 using the test data.

"""

from sklearn.linear_model import Ridge

from sklearn.linear_model import Ridge

# Create a Ridge regression object with alpha = 0.1
ridge_model = Ridge(alpha=0.1)

# Fit the model using the training data
ridge_model.fit(x_train, y_train)

# Calculate the R^2 using the test data
r2_ridge = ridge_model.score(x_test, y_test)

# Print the R^2 score
print("R^2 for Ridge regression on test data:", r2_ridge)

"""### Question 10

Perform a second order polynomial transform on both the training data and testing data. Create and fit a Ridge regression object using the training data, set the regularisation parameter to 0.1, and calculate the R^2 utilising the test data provided. Take a screenshot of your code and the R^2.

"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score

# Create a PolynomialFeatures object with degree 2
poly_features = PolynomialFeatures(degree=2)

# Transform the training and testing data
x_train_poly = poly_features.fit_transform(x_train)
x_test_poly = poly_features.transform(x_test)

# Create a Ridge regression object with alpha = 0.1
ridge_model_poly = Ridge(alpha=0.1)

# Fit the model using the transformed training data
ridge_model_poly.fit(x_train_poly, y_train)

# Calculate the R^2 using the transformed test data
r2_ridge_poly = ridge_model_poly.score(x_test_poly, y_test)

# Print the R^2 score
print("R^2 for Ridge regression with polynomial features on test data:", r2_ridge_poly)

"""<h2>About the Authors:</h2>

<a href="https://www.linkedin.com/in/joseph-s-50398b136/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDA0101ENSkillsNetwork20235326-2022-01-01">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

Other contributors: <a href="https://www.linkedin.com/in/michelleccarey/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDA0101ENSkillsNetwork20235326-2022-01-01">Michelle Carey</a>, <a href="https://www.linkedin.com/in/jiahui-mavis-zhou-a4537814a?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDA0101ENSkillsNetwork20235326-2022-01-01">Mavis Zhou</a>

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By      | Change Description                           |
| ----------------- | ------- | --------------- | -------------------------------------------- |
| 2022-07-29        | 2.3     | Lakshmi Holla | Added library import |
| 2020-12-01        | 2.2     | Aije Egwaikhide | Coverted Data describtion from text to table |
| 2020-10-06        | 2.1     | Lakshmi Holla   | Changed markdown instruction of Question1    |
| 2020-08-27        | 2.0     | Malika Singla   | Added lab to GitLab                          |

<hr>

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>

<p>
"""